language: go

go:
  - 1.9.1

install:
  - sh scripts/run_glide_up
  - sh scripts/build

script:
  - sh scripts/run_glide_up
  - sh scripts/run_units.sh

notifications:
          slack: ibm-ubiquity:90NYAcW9cL2tICCmA8RITQis
